# <a id='7'>Write a function so that the columns of the output matrix are powers of the inputvector.</a>

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the 
i-th output column is the input vector raised element-wise to the powerof N - i - 1.

In [1]:
import numpy as np
import pandas as pd

In [2]:
x = np.array([1, 2, 3, 5])
N = 3

In [3]:
result = np.vander(x)
print('Vander with Only Array :\n'  , result)

Vander with Only Array :
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [4]:
result2 = np.vander(x, N)
print('NP Vander with Array and N Values: \n' , result2)

NP Vander with Array and N Values: 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]


In [5]:
result3 = np.column_stack([x**(N-1-i) for i in range(N)])
print('NP Vander with Power (N-1-i) : \n' , result3)

NP Vander with Power (N-1-i) : 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]


In [6]:
result4 = np.vander(x, increasing=True)
print('NP Vander with Increasing True :\n' , result4)

NP Vander with Increasing True :
 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


In [7]:
result5 = np.vander(x, increasing=False)
print('NP Vander with Increasing True : \n' , result5)

NP Vander with Increasing True : 
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


## [Task 2](#0)

# <a id='7'># Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 12345678910
===== ====================
Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.


# Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.</a>


In [8]:
df = pd.DataFrame({'Variables' : [3,5,7,8,10,11,65,72,81,99,100,150]})
df['Rolling'] = df.rolling(window=3 , min_periods=2).mean().round(2)
df.head()

Variables  Rolling
0          3      NaN
1          5     4.00
2          7     5.00
3          8     6.67
4         10     8.33

# Done